sudo: required
services:
  - docker

before_install:
  - chmod +x test.sh

script:
  - ./test.sh

after_success:
  - bash <(curl -s --retry 5 --retry-delay 2 --connect-timeout 2 https://codecov.io/bash)
