version: '3'

services:
  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    logging:
      driver: none
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=complete_tabs
  test-runner:
    depends_on:
      - db
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - 3333:3333
    environment:
      - PG_CONN_STRING=postgres://postgres:password@db:5432/complete_tabs
    command: npm run test
